### ISSUE TITLE
Error when launching vcftools

### ISSUE THREAD

**Issue by lecorguille** [vcftools/vcftools#34] opened 2016-02-25 11:36 UTC
Hi,

I have just compil the master branch of vcftools.

Although, the compilation succeded, when I launch the binary, I get that :

```
$ ./vcftools
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct NULL not valid
Aborted (core dumped)
```

Distribution : CentOS 6
gcc -v : gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

vcftools_0.1.12 works find.

**Comment by auton1** [comment] 2016-02-28 20:20
I think this is caused by this change: https://github.com/vcftools/vcftools/pull/33

Will see if I can put in a fix.

**Comment by auton1** [comment] 2016-02-28 20:26
I have checked in a change. I would be grateful if you could check it out, and let me know if it fixes the issue. Thanks.

**Comment by chlangley** [comment] 2016-02-29 01:03
> On 28/Feb/2016, at 12:26 PM, Adam Auton <notifications@github.com> wrote:
> 
> I have checked in a change. I would be grateful if you could check it out, and let me know if it fixes the issue. Thanks.
> 

Hello:

I checked out #34, compiled and installed it.

_________________________________________________________________________
| DPGP3b_GVCF @ rootless6 (chuck)
| => vcftools --vcf DPGB3b_2L12-13Mb_GVCF_h006-0006vO.g.vcf --window-pi 500

VCFtools - 0.1.15
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--vcf DPGB3b_2L12-13Mb_GVCF_h006-0006vO.g.vcf
	--window-pi 500

After filtering, kept 187 out of 187 Individuals
Outputting Windowed Nucleotide Diversity Statistics...
	windowPi: Only using fully diploid sites.
After filtering, kept 139387 out of a possible 139387 Sites
Run Time = 15.00 seconds
_________________________________________________________________________


but 
_________________________________________________________________________
| => cat out.windowed.pi
CHROM	BIN_START	BIN_END	N_VARIANTS	PI
_________________________________________________________________________

no windows output to the file.

Hopefully I am applying vcftools correctly.  My input vcd is a multisample GCVF. 

I notice it still states  “windowPi: Only using fully diploid sites.” 
But my data is haploid.

Cheers, 
chl

**Comment by lecorguille** [comment] 2016-03-02 10:50
It seems good. I can get the welcom message when I run the vcftools binary.

Now, I will ask to my colleague to test it. I will forward you her returns as soons as possible.

Thanks

**Comment by lecorguille** [comment] 2016-03-02 11:35
My colleagues have just tested this new version and the --mendel option.

They are very thankfull and ... enthusiastic!

Thanks again

**Closed** 2016-03-05 23:20 UTC
