### ISSUE TITLE
warning old zlib but ldd shows new zlib

### ISSUE THREAD

**Issue by map2085** [vcftools/vcftools#62] opened 2016-10-21 21:02 UTC
When I run vcftools, it complains about an old version of zlib (1.2.3).

But I locally installed a new version of zlib (1.2.8), modified `pkg-config` to point to my new local installed zlib, verified that config.log for vcftools found the new zlib, and even `ldd` shows that vcftools is linked to the new zlib.

`$  vcftools  --gzvcf  ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz  --indv  HG00096    --out  my.out`

> VCFtools - 0.1.15
> (C) Adam Auton and Anthony Marcketta 2009
> 
> Parameters as interpreted:
>     --gzvcf ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
>     --out my.out
>     --indv HG00096
> 
> Using zlib version: 1.2.3
> Versions of zlib >= 1.2.4 will be _much_ faster when reading zipped VCF files.
> Keeping individuals in 'keep' list
> After filtering, kept 1 out of 2504 Individuals

However, `ldd` shows that it uses my new zlib

`$ ldd  vcftools`

> ```
> linux-vdso.so.1 =>  (0x00007fff811ec000)
> libz.so.1 => /zenodotus/scratch/map2085/packages/zlib/lib/libz.so.1 (0x00007f3ef9362000)
> libstdc++.so.6 => /zenodotus/scratch/map2085/packages/pandasoft-gcc/gcc/gcc-4.8.4/lib64/libstdc++.so.6 (0x00007f3ef9059000)
> libm.so.6 => /lib64/libm.so.6 (0x0000003b52400000)
> libgcc_s.so.1 => /zenodotus/scratch/map2085/packages/pandasoft-gcc/gcc/gcc-4.8.4/lib64/libgcc_s.so.1 (0x00007f3ef8e17000)
> libc.so.6 => /lib64/libc.so.6 (0x0000003b51c00000)
> /lib64/ld-linux-x86-64.so.2 (0x0000003b51400000)
> ```

indeed, the zlib pointed to is very new:

`$ ls -lh /zenodotus/scratch/map2085/packages/zlib/lib`

> total 352K
> -rw-r----- 1 map2085 blab 124K Nov  6  2014 libz.a
> lrwxrwxrwx 1 map2085 blab   13 Nov  6  2014 libz.so -> libz.so.1.2.8
> lrwxrwxrwx 1 map2085 blab   13 Nov  6  2014 libz.so.1 -> libz.so.1.2.8
> -rwxr-x--- 1 map2085 blab  97K Nov  6  2014 libz.so.1.2.8
> drwxr-x--- 2 map2085 blab  32K Nov  6  2014 pkgconfig

This was achieved by appending to PKG_CONFIG_PATH in .bashrc

`export  PKG_CONFIG_PATH="$ZLIB/lib/pkgconfig:$PKG_CONFIG_PATH"`

And it was correctly found during `configure` of `vcftools`

From config.log  for `vcfctools`:

> pkg_cv_ZLIB_CFLAGS='-I/zenodotus/scratch/map2085/packages/zlib/include  '
> pkg_cv_ZLIB_LIBS='-L/zenodotus/scratch/map2085/packages/zlib/lib -lz  '

`$ vcftools  --version`

> VCFtools (0.1.15)

**Comment by wookietreiber** [comment] 2016-10-21 21:38
The `pkg-config` stuff is only used during compilation / linking. Even though you *compiled* and *linked* with your zlib build, when the shared library is *loaded*, it finds only the older version within your default paths.

Thus, you need to also point your `LD_LIBRARY_PATH` environment variable to your zlib build. This environment variable contains a colon-separated list of paths where libraries are located:

```bash
$ export LD_LIBRARY_PATH=/zenodotus/scratch/map2085/packages/zlib/lib
$ vcftools ...
```

---

FYI: Paths like `/usr/lib` are automatically included in the search when shared libraries are loaded. For more information, see `man 8 ld.so` and `man 8 ldconfig`.

**Comment by map2085** [comment] 2016-10-21 21:54
Good point.
But unfortunately, this still did not work...
same warning message


` $ echo -e "$LD_LIBRARY_PATH"  | tr ':'  '\n'`
```
/zenodotus/blanchardlab/scratch/map2085/packages/zlib/lib
...
```

**Comment by map2085** [comment] 2016-10-21 22:04
` $ readelf  -d    $VCFTOOLS`

> Dynamic section at offset 0xce100 contains 27 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
>  0x000000000000000f (RPATH)              Library rpath: [/zenodotus/blanchardlab/scratch/map2085/packages/libxml2/lib]
>  0x000000000000000c (INIT)               0x4049a8
>  0x000000000000000d (FINI)               0x4b2238
>  0x0000000000000019 (INIT_ARRAY)         0x6ce038
>  0x000000000000001b (INIT_ARRAYSZ)       160 (bytes)
>  0x0000000000000004 (HASH)               0x400240
>  0x0000000000000005 (STRTAB)             0x401da8
>  0x0000000000000006 (SYMTAB)             0x4008d8
>  0x000000000000000a (STRSZ)              5490 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000015 (DEBUG)              0x0
>  0x0000000000000003 (PLTGOT)             0x6ce308
>  0x0000000000000002 (PLTRELSZ)           4488 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0x403820
>  0x0000000000000007 (RELA)               0x4035c8
>  0x0000000000000008 (RELASZ)             600 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffe (VERNEED)            0x4034d8
>  0x000000006fffffff (VERNEEDNUM)         5
>  0x000000006ffffff0 (VERSYM)             0x40331a
>  0x0000000000000000 (NULL)               0x0


It seems like the `rpath` is off.  Do I specify `rpath` this during `configure` for vcftools?

**Comment by wookietreiber** [comment] 2016-10-22 08:53
I'm wondering how the rpath came to be in the first place. Do you have any of `CFLAGS`, `CXXFLAGS` or `LDFLAGS` set? Did you do anything special during `configure` that you are using rpath? On which platform are you?

**Comment by map2085** [comment] 2016-10-22 13:20
` $ cat  /etc/redhat-release 

> `Red Hat Enterprise Linux Server release 6.3 (Santiago)


I have LD_RUN_PATH set for another application

`export  LD_RUN_PATH=/zenodotus/scratch/map2085/packages/libxml2/lib${LD_RUN_PATH+:$LD_RUN_PATH}
`

I tried compiling vcftools even by appending libz to LD_RUN_PATH:

`export LD_RUN_PATH=$ZLIB/lib${LD_RUN_PATH+:$LD_RUN_PATH}
`
(after the above export to LD_RUN_PATH relating to libxml2)

Same error.





I even tried static linkage to my zlib 1.2.8

```
$ ZLIB_LIBS=' /zenodotus/scratch/map2085/packages/zlib/lib/libz.a  '
./configure
make
```

Still same warning about old zlib 1.2.3

**Comment by map2085** [comment] 2016-10-22 13:28
LDFLAGS, CXXFLAGS, CFLAGS are all unset.
At configure, i only gave a --prefix argument.

**Comment by map2085** [comment] 2016-10-22 13:31
Note, when I statically link zlib as above:
 `ZLIB_LIBS=' /zenodotus/scratch/map2085/packages/zlib/lib/libz.a  '`

Then `readelf` does not even say that libz is dynamic, yet vcftools still gives warning.


`$ readelf  -d  ./src/cpp/vcftools
`

> Dynamic section at offset 0xdfaa0 contains 26 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
>  0x000000000000000f (RPATH)              Library rpath: [/zenodotus//scratch/map2085/packages/libxml2/lib]
> ..... etc

**Comment by map2085** [comment] 2016-10-22 13:34
Further, if I set LD_RUN_PATH for zlib:

`export LD_RUN_PATH=$ZLIB/lib${LD_RUN_PATH+:$LD_RUN_PATH} `

and then set ZLIB_LIBS as usual

` export  ZLIB_LIBS="  -L$ZLIB/lib  -lz  " ; `

Then `readelf` now gives the proper location RPATH:

` $ readelf  -d  ./src/cpp/vcftools
`
> Dynamic section at offset 0xce140 contains 27 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
>  0x000000000000000f (RPATH)              Library rpath: [/zenodotus/scratch/map2085/packages/zlib/lib:/zenodotus/scratch/map2085/packages/libxml2/lib]


yet vcftools gives the same old zlib error.

**Comment by map2085** [comment] 2016-10-22 13:45
could you release pre-compiled binaries that have the new zlib?  lots of people seem to have zlib-related problems

**Comment by Lu-Tze-Jr** [comment] 2016-10-24 17:00
The problem seems to be in the src/cpp/Makefile.

Both ZLIB_CFLAGS & ZLIB_LIBS are populated correctly via pkg-config, but further down in the Makefile this happens:
`vcftools_CPPFLAGS = $(ZLIB_CPPFLAGS)`

As ZLIB_CPPFLAGS isn't defined anywhere, no local include-path is used. At least in my case, this lead to the right **library** being linked, but since the systems (CentOS) old header file for zlib was used, version information (1.2.3) was taken from there, and some more recent functions (like `gzbuffer()`) couldn't be found. I'd classify that as sneaky... :-)

As I built from git pull, I solved it by running:
` env CPPFLAGS="-I/MY/PATH/TO/ZLIBINCLUDE" ./configure`

I'm not into the auto-tools enough to pinpoint where to correct this properly, but I guess it's fairly simple for someone who is.

**Comment by wookietreiber** [comment] 2016-10-25 13:12
Oh, then I know, what the problem is: It must be `ZLIB_CFLAGS` instead of `ZLIB_CPPFLAGS`. I'll provide a PR shortly.

**Comment by wookietreiber** [comment] 2016-10-25 13:18
@map2085 Would you please verify my patch works by locally applying it and checking if it solves the issue?

**Comment by Lu-Tze-Jr** [comment] 2016-10-25 14:02
@wookietreiber This patch seems to work fine, solves the issue for my build & installation.

**Comment by wookietreiber** [comment] 2016-10-25 15:10
Great, then, hopefully, it gets merged soon.

**Comment by wookietreiber** [comment] 2016-10-25 16:30
#60 got merged, so, I guess, this issue can be closed now.

**Closed** 2016-11-11 23:01 UTC
